### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by FabianEllenberger** [hideakitai/TFmini#1]
He there,

I'm using your library successfully, but i can't get the configurations working.
how can i use: `void setOutputDataUnit(const OutputDataUnit unit)` for example?

i tried the following, but had no results (also no errors):
```
TFmini::OutputDataUnit col = TFmini::OutputDataUnit::MM;
tfmini.setOutputDataUnit(col);
```

Other funnctions, such as `tfmini.available()` or `tfmini.getDistance()` wor perfectly fine.

Thanks in advance and great library by the way! 🙏

**Comment by hideakitai** [comment]
@FabianEllenberger I'm so sorry for late reply... I think this can be compiled.
```
tfmini.setOutputDataUnit(TFmini::OutputDataUnit::MM);
```
Thanks for your feedback!
